apiVersion: v1
kind: Service
metadata:
  name: anomaly-detection
  namespace: logguard
  labels:
    app: anomaly-detection
spec:
  type: ClusterIP
  ports:
    - port: 8001
      targetPort: 8001
  selector:
    app: anomaly-detection
