apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: logguard
type: Opaque
data:
  # base64 encoded values â€” update before deploying
  # echo -n 'logguard_password' | base64
  POSTGRES_PASSWORD: bG9nZ3VhcmRfcGFzc3dvcmQ=
  # echo -n 'logguard_user' | base64
  POSTGRES_USER: bG9nZ3VhcmRfdXNlcg==
  # echo -n 'logguard_db' | base64
  POSTGRES_DB: bG9nZ3VhcmRfZGI=
